#+TITLE: 2014 年终总结
#+OPTIONS: author:nil timestamp:nil creator:nil
#+OPTIONS: \n:t

时间真是过得越来越快，这一年匆匆而过，年初的目标到年底早已不再是目标。记得年初的时候还在开淘宝店，那时候的目标是年底营业额达到****，到了后半年就从北京来到了深圳，找了新工作，淘宝店也没时间弄了，老板娘也没有了。。。

年初还定了其他三个项目目标，一月一本书，到年底common lisp可以熟练应用，每月出去任性一次。

* 看书
  今年看得书有：1984，麦田里的守望者，蝇王，黑客与画家，白鹿原，1988：我想和这个世界谈谈，青铜时代，遇见未知的自己，史蒂夫乔布斯传，时间简史。大多应该是初高中读本。。。谁让咱年轻时浪费了时间，现在能补多少就补多少吧：）。好多书看过一遍，过了一阵子就忘记了，但我相信有些东西会沉淀下来，只是你还不知道，厚积薄发。还有一些技术书籍还在看的，不知道明年可否能看完。。SICP，On Lisp，计算机科学导论。下面简单回忆下对书的印象吧。
  最近看完的是《乔布斯传》，看过之后是很想买台mac来感受下的，也觉得苹果之后再无“苹果”了，现在很多人都在说苹果好，这其中一部分人或许连摸都没有摸过苹果手机，大部分人应该是因为品牌效应而认为苹果好的。为什么我说苹果之后再无“苹果”了呢，有几点原因，1，乔布斯对完美，简洁极致的追求。2，他是苹果的boss。3，苹果并不是只创造出一款伟大的产品，而是一直引领未来，创造出一个又一个的奇迹，改变了多个行业格局，真的很难。世界上像乔布斯这样极致的人应该不多，在科技行业的就更少，如果乔布斯在中国，他很可能被扼杀在摇篮里，一辈子郁郁而终，就算是在美国，如果他没有和沃兹一起创造出苹果公司，而是通过给别人打工，那么是否出头，或何时出头就成了一个问题。
  1984，必看的书，书中描写的情景，和现实是惊人的相似，应该对现在的生活有更深刻的理解。
  麦田里的守望者，应该是初中读本吧，书中的男主和我某些方面比较像，最后一幕，他在雨中看着妹妹玩旋转木马，高兴的不得了。我能了解他的心情。
  蝇王，关于人性的一本书，有时文明在暴力面前就是那么的不堪一击。
  黑客与画家，很好的一本书，当初看得时候只是简单看的，有机会还得再翻翻，通过这本书我了解了lisp，并义无反顾的跳进坑里，哈哈，就是想好奇某些人评价这么高的语言，究竟有什么魅力。现在还在学习中。。。
  白鹿原，书中刻画人物非常好，很多人的一生都在一本书中体现出来，每个人物个性鲜明，结合时代大背景，上演了一场大戏。
  1988：我想和这个世界谈谈，有点忘记了。
  青铜时代，讽刺的非常好，但看过青铜时代之后再看白银或其他的，总感觉有些重复的感觉。。。（沉默的大多数也不错哦）
  遇见未知的自己，看了两遍，第一遍当小说看，没明白，又看第二遍，似乎明白了：）。书中写了“心想事成”的秘诀，一般人我不告诉他。
  时间简史，看不太懂，当小说看了一下，有一些话题还是很有趣的，比如时间和空间是否有开端，时间是绝对的还是相对的等
  大概就这么多了吧，其他的可能也不记得了。。。

* Common Lisp
  这个我现在还在坑中，等我出来的，详细说下，哈哈。目前在看SICP和On Lisp，递归写的那叫一个顺啊。我这人啊，确实做事有点慢，但没办法既然慢就做好吧。最近也是实在太忙，公司要出手机，弄得天天加班，最近已累的不成人形。

* 每月任性一次
  就不是一个任性的人！

* 总结
  目标完成的不好，但是，总会有但是，我又找到了方向（是的，我的方向总是在变，不，在调整）。我终于找到了“成功”的捷径，就是坚持，努力，我觉得这是我今年来最大的收获。还有就是学会专注，懂得抛弃不重要的，让目标变得清晰，保持专注。明年就继续坚持以上两条原则就好。

* 新年目标
  虽然在这里列目标有点扯，因为计划总是没有变化快，但还是展望一下。明年继续努力，学习CommonLisp，SICP，努力工作，看书，要养成冥想习惯，在这个浮躁的世界，这个习惯太重要了。恩，就这些了。
