#+TITLE: 你好，深圳
#+OPTIONS: ^:{}

8月中旬来到了深圳，到现在基本都稳定下来，还是不错的。

在北京也待了很久，也没有白待，思考明白了，自己要怎么去努力，去坚持，接下来就是实践。

生活上，终于和女朋友分手了，诺大的深圳就剩我一人了，来深圳的目的也没有了，只能努力工作了。还好工作进行的还不错，节奏也蛮好。

原来深圳这么多“裸房”，北京很少有的，到现在洗衣机，冰箱还没买呢。深圳也不太适合骑车，压根就没有自行车道。交通比北京贵些，话说北京坐公交才4毛。环境比北京好，常下雨，绿化也好，到处都是绿色。下班也比较堵，但跟北京比起来是小屋见大屋，交通算是便利的了。

最近在看<<1984>>，正好又看了电影 V字仇杀队，不错，推荐。你看这博客小图标都换成V了，哈哈。

该下班，吃饭去了。

昨晚写的一封邮件想今天发，现在看起来，还是太年轻，所以不发了，做个记录，留以后审阅
#+BEGIN_QUOTE
关于昨天会议，我觉得有一个严重的流程问题，这里有必要提一下。

问题
昨天会议由我叙述需求，直接跳到了讨论一定要做别人没有的东西。中间少了一个至关重要的环节，就是大家思考我做的这些需求是否已经构成了一款好的产品，而直接要做别人没有的东西。我觉得这是一个非常严重的问题，直接关系到我们做其他产品的态度及其他产品最终的样子。


以下是我的观点

这个产品需求我是很认真做的，也相信如果按照这个走下去到交互，编码出产品，在简单便捷实用的定位上(我还是坚持我的定位)，绝不逊色市场上其他产品。我是认真的！

那么问题严重在哪里？

大家跳过了思考这些需求构成产品是否ok，而直接讨论要有别人没有的。就证明我们做产品第一目标是要做别人没有的，说到这大家觉得可能没什么，但是我们真正的目标是做一款伟大的手机，进而做很多优秀的产品，在桌面上也就是说目标是要做一款优秀的产品。而现在我们第一目标变了，这会导致什么后果？

我们按照这个方向，或许我们做出了一款优秀的手机，但绝做不出一款伟大的手机。


出现这样情况的原因可能有两点∶
1. 我不专业，让我做这些需求就是要我做些差异点亮点而已，大家压根就不觉得我还能做出一款产品，所以跳过了思考这些需求是否可以构成产品
2. 大家真的觉得最重要的就是要做出跟别人不一样的地方
希望是第一点。


对于桌面的这款产品，我认为市场相对成熟，所做创新不多，更多是需求微创新和交互上的便捷，即便是微创新也相对较难想出(我指的是精彩实用的创新)，那么大家再做产品需求时候，就不要一定要想出个创新，第一任务是先把这个做完美，创新可能是在你无意间想出来的想法。


一点愚见

大家可能之前都在其他手机大厂商那里工作过，相信他们模式大多数都一样，做加法，他们很成功吗？我们能不能反其道，做减法，产品做到极致，我们更容易看出该创新的点在哪里，因为我们产品全是实用的功能。

做减法有两点好处
1. 我们可以更专注做产品的每一个功能，不断打磨它。
2. 我们有更多时间去思考创新。而其他厂商花很多时间要去做跟别人不一样。


最后

抱歉不能和大家当面讨论，我这人属于后知后觉，用邮件会多些思考时间，想法相对成熟。

我之前是做应用的，现在把自己定位成一个做手机的。真的希望能和大家一起做出一款让自己感到牛逼，骄傲的手机！
#+END_QUOTE

这里我提出的我们真正的目标，还是太年轻，这个概念太虚，虽然我不认同现在具体的做法（一定要找出差异点），但我提出这个比较虚的目标，还是不切实际的。虽然有些想法还是可取，但总体方案没有评判的标准，难以实行。但确实不应该定为一定要有差异点。从自己这里努力吧，自己强大后，有了更多话语权，再去实践我的标准，哈哈！
